services:
  web:
    build: .
    container_name: grace-backend
    command: daphne -b 0.0.0.0 -p 8000 grace_backend.asgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery:
    build: .
    container_name: grace-celery
    command: celery -A grace_backend worker --loglevel=info --pool=solo
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: grace-celery-beat
    command: celery -A grace_backend beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    restart: unless-stopped
