# Generated by Django 4.2 on 2025-06-29 17:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('session_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('rating', models.FloatField(default=0.0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='therapists/photos/')),
                ('languages', models.JSONField(blank=True, default=list)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50)),
                ('available_from', models.TimeField(default=datetime.time(9, 0))),
                ('available_to', models.TimeField(default=datetime.time(17, 0))),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
                ('notify_on_booking', models.BooleanField(default=True)),
                ('notify_on_cancellation', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapistprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TherapistAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='therapists.therapistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TherapistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_requests', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='therapists.therapistprofile')),
            ],
            options={
                'unique_together': {('patient', 'therapist')},
            },
        ),
    ]
