# Generated by Django 4.2 on 2025-07-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device token', max_length=255, null=True),
        ),
    ]
